{% set name = "fastcluster" %}
{% set version = "1.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fastcluster-{{ version }}.tar.gz
  sha256: aab886efa7b6bba7ac124f4498153d053e5a08b822d2254926b7206cdf5a8aa6

build:
  number: 0
  script: pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - numpy {{ numpy }}
    - setuptools
    - wheel
    - pip
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - fastcluster
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://danifold.net/fastcluster.html
  license: BSD-2-Clause AND GPL-2.0-or-later
  license_file: COPYING.txt
  summary: Fast hierarchical clustering routines for R and Python
  description: |
    This library provides Python functions for hierarchical clustering. It generates hierarchical
    clusters from distance matrices or from vector data.
    Part of this module is intended to replace the functions
    linkage, single, complete, average, weighted, centroid, median, ward
    in the module scipy.cluster.hierarchy with the same functionality but much faster algorithms.
    Moreover, the function linkage_vector provides memory-efficient clustering for vector data.
    The interface is very similar to MATLAB’s Statistics Toolbox API to make code easier to
    port from MATLAB to Python/NumPy. The core implementation of this library is in C++ for efficiency.
  dev_url: https://github.com/dmuellner/fastcluster
  doc_url: https://github.com/dmuellner/fastcluster/raw/master/docs/fastcluster.pdf

extra:
  recipe-maintainers:
    - mpharrigan
