travis:
  secure:
    BINSTAR_TOKEN: yA2pj/xKD5rCiQ0SMXSxzmAOyGCLWh37dPleL3qsyUikBaVL3Cg3o5T+KtLugoZzm91EW/c0N1VtytF3TDkh5/qx4ou1wdUR5ZiaRJjKy+ug/AiCO7tqCNb92yJRk7f4eD3JsLIA3wT/nGec3UUGqceBbz9RfMpBPSepZxMk25BEdt5BazHygXZrqnUPpD/XsPDyABZYx/W801jOvBK772cO6EHbOaUVHOvDzQfdt4Y0MNf5ei+0TpABDMMbTcU6tzt+ebiZVnIisSolJYZ1jBG1M6REnjp70YzvY4odU6Du9L+dLfIDo1B7ocCvhn8WlbWMko4JtAPaWCsFg7bs+0WAXUTN+Xy5bDGyWr0vbVOBgFplEPaweUxbsUFt+mBvQICP0gBSOAz9Q6i3ctXh8ql8uSVCUZtcSVWmflWOj9go0JunN61sXDs8DeRDdzZHWzEnXG06K2FG4hb1ZdTT6NcHlgEcbu9ewrF/osvVvBM+GWhdLWuHVGfXdXcRkJwBPXLNIdqmMv4h/JnIC1Y7dePBB06W/8jKmU0ZLcbS3K+qqJIAzxLT6Kd/w1VsVb2uL3092vNnWzdK7RUb2qyebNWXTzIjfke0a6he7k32Xtl1QCIIAelGrOgQaDuSpn4pOfG8xYlugY9xGJT3dZCQGrSSifzkt2HjPPlzDS8GbG0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
