travis:
  secure:
    BINSTAR_TOKEN: KuXYXvF2pYGMExHAZdVI4IqMKzR4DdXyP6zq5vq5F4DI1U2JcKxIs/KhwTH0HSQb3gZZ8pE7QQ4jV2dWYlBj5Nz4jByGvLWMkVOa8auvyevLSGf2EcKXwlrf0rnRyvpq1vneWsZL6Rt+x/xkTYkDlmaUyudj378cCDAexXDdLwzk2kTGwF6QBmSjGfmTjn5X1DNY2zMH3SdNNs4zoUvmjxcRsl4PoolYrexLz5+1cI3HQuTSn6a4nAVsbG3RaSAfy7mejP/YlfU+UmbwjsuE+zAgL3G4sNWf685bdwMQlR5zc/j1w9nXahnWEXbS7AZkDlYHxKg2fWzRuGfDoyW7SQlPrEaubA6+vW6fTjjZqDRjZwjTR21Et6LZ6YljxzlmQydFeXhWrnI5zS4MF25BtPvXNhpurPeffi8MdLn2KP7IPO3BDMJeQwPdQpIj8y6ycTYmQST47OTI4z8NjATN6vOJNrYvljFsQ/3olH6wqf6u5mbFv4MEWL/UGLnMQ+NS7XupbhUlPILqvduXlJBC4KuSnDpukHXI/Hycee5a+7//eZ+gn3F5GhZOsE7/PvH7ZryzyX+6rwir3xmaXaHunWWemT7j3hjILKvXJDliv6RcHZRIjsMlnVPbqfOjg+0jRhqwKNT7uZnPf1uUUVU3b9pArdvFp5PMMg/wvJ/Zgv0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
