appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: dGJzkInhVsBewpKZJtwTCffppe2WlauQvo94mmE8MLO/qCSElu5eKprc1kbVWjpM8+gWzPAaFA2TxPDJhF0nLARE1+du0wWiU/zjlI3g2XpIyXPn52W72cPOzzhpQCS9Syrpv7aKG4MFMa+u9XYXA9HTLUr7XtluAKl+qrEPw7wQBPCZ6a3iL0U1wyEd7s2mNFHtVQ4f69Z2kRNBbkCKbWIUMRD62Tza5IEprE5LVGwnAKkkD25/OTSV7jZeQSJ48v+21yEv3rqeOryIAhtiwYaxkSatiOHaKf9pSW+pwRaUlc6PTWZOGMcpl/hcuu4TuG8xn+Qt2Ij5rOgb84gTwwFXGZ983CXQx4Kj4jQTTux0REZFN2QH+203OUSqdXCDS+pl3de0tRJsyHNeLRHAHx96fGHEQGpkTBe5ly4aW5Y0K/bnvWi8Ex6mR+5c4rHBin9ORy+SKAf0pCO49yK5WUzF2nJHrsJExV2RNtMAuhIPNZI+S1TrP0O3VWppQGS4zAMABcif9AvMNtIfHaqKFK06Dnhid+a86LZPpkSB6lavZ+F/Rr9zbCnZH4VTwte0yzYhxAzyM2JVtMun0VEE6ibS3t0KOyKgj5ZvDTyKnjpyiFGCivrzujXDXBHFIpVpPOwTOmPZf+LepLsyOZc1KLxel9+m+9Fs0sBnT4xTfx8=}
conda_forge_output_validation: true
